name: My first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello world!!!!"
      - name: Print multiple lines
        run: |
          - echo "1st. Line"
          - echo "2nd. Line"
      - name: Print Goodbye
        run: echo "Goodbye!"